modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/ImBonana/SelfieCamMod/issues"
license = "MIT"

[[mods]]
modId = "selfiecam"
version = "${version}"
displayName = "SelfieCam"
authors = "ImBanana"
description = '''
A mod that add a selfie camera
'''
logoFile = "assets/selfiecam/icon.png"
modUrl = "https://modrinth.com/project/selfiecam"

[[dependencies.selfiecam]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.selfiecam]]
modId = "minecraft"
type = "required"
versionRange = "${mc_version_range}"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "selfiecam.mixins.json"
